apiVersion: v1
kind: ConfigMap
metadata:
  name: front-end-config
data:
  NEXTAUTH_URL: "https://front-end.smart-nextgen.com/"
  KEYCLOAK_ISSUER: "https://keycloak.example.com/realms/myrealm"
  KEYCLOAK_CLIENT_ID: "nextjs-frontend"
  NEXT_PUBLIC_API_URL: "https://nextgen-api.smart-nextgen.com/"