apiVersion: v1
kind: LimitRange
metadata:
  name: nextgen-limits
  namespace: nextgen
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"


