apiVersion: batch/v1
kind: Job
metadata:
  name: db-config
  namespace: nextgen-gitops
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure

      volumes:
        - name: data-volume
          configMap:
            name: db-config

      containers:
        - name: db-init
          image: postgres:15
          imagePullPolicy: IfNotPresent

          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e

              echo "Waiting for PostgreSQL..."
              until pg_isready -h postgresqldb -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do
                sleep 2
              done

              echo "Creating tables"
              psql -h postgresqldb -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
                   -f /etc/dbvolume/build_tables.sql

              echo "Loading data"
              psql -h postgresqldb -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
                   -f /etc/dbvolume/data.sql

              echo "Database initialization completed successfully"

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-name
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-password

          volumeMounts:
            - name: data-volume
              mountPath: /etc/dbvolume
