apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: smart-gen
  labels:
    app: postgresql
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: postgresql-data
          emptyDir: {}
      containers:
        - name: postgresql
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-name
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER"
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER"
            initialDelaySeconds: 30
            periodSeconds: 10
      terminationGracePeriodSeconds: 30
---
kind: Secret
apiVersion: v1
metadata:
  name: postgresql
data:
  database-name: bmV4dGdlbg== #nextgen
  database-password: QzBtcGxleFBAc3N3MHJk #C0mplexP@ssw0rd
  database-user: bmV4dGdlbg== #nextgen
type: Opaque
---
kind: Service
apiVersion: v1
metadata:
  name: postgresqldb
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: postgresqldb
      protocol: TCP
      port: 5432
      targetPort: 5432
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: postgresql
