apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextgen-api
  namespace: nextgen-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextgen-api
  template:
    metadata:
      labels:
        app: nextgen-api
    spec:
      containers:
        - name: nextgen-api
          image: quay.io/wael2000/nextgen-api
          ports:
            - containerPort: 8080
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-name
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-password
            - name: POSTGRESQL
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: POSTGRESQL
            - name: QUARKUS_PROFILE
              value: prod