apiVersion: v1
kind: Secret
metadata:
  name: educates-credentials
  namespace: nextgen-gitops
type: Opaque
stringData:
  EDUCATES_BASE_URL: https://nextgen-portal-ui.workshops.smart-nextgen.com
  EDUCATES_CLIENT_ID: replace-me
  EDUCATES_CLIENT_SECRET: replace-me
  EDUCATES_USERNAME: replace-me
  EDUCATES_PASSWORD: replace-me
  NEXTGEN_PORTAL_URL: https://front-end.smart-nextgen.com
