apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  USERNAME: postgres@postgresqlserver-nextgen
  PASSWORD: C0mplexP@ssw0rd
  POSTGRESQL: postgresqlserver-nextgen.postgres.database.azure.com